### ISSUE TITLE
[GBA] Pokemon emerald rogue 2.0.1a - An unhandled instruction error

### ISSUE THREAD

**Issue by mattatticus** [skylersaleh/SkyEmu#501]
Hello.

While i was running pokemon emerald rogue, when I try to catch my starter the game just closed.

I ran it from a terminal and I got:

Coprocessor Write Issued without bound coprocessor_write handler: eee5e6f9
Unhandled Instruction Class (arm7_coproc_data_transfer) Opcode: fdf1eff9

Note: I didn't run it with a bios firmware.

#### Version: SkyEmu 3-1 (installed from aur)

**Comment by skylersaleh** [comment]
I think this was fixed in the dev branch. 

Can you try the builds here: https://github.com/skylersaleh/SkyEmu/pull/321  ?

**Comment by mattatticus** [comment]
Let me give it a try.

**Comment by mattatticus** [comment]
No it seems the issue is still there. Let me try building it from source and notify you later.

**Comment by skylersaleh** [comment]
Hmm, I was just able to reproduce the issue on the web build of dev. I wonder why I can't reproduce it on my local build of dev.

**Comment by skylersaleh** [comment]
Okay, I think this may be an issue in the open source replacement BIOS. It appears the game is just flat out crashing. I was able to successfully enter the first pokemon battle 4 times using the official BIOS. Can you try using an official BIOS on your side? 

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/1630aaf1-fb4f-4bac-90c1-db6cb8272f60" />

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/a8e93559-e53f-47a3-a695-3963f7eb5c72" />

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/d887b21d-d0d4-4e3f-9781-9ece7fcbdd63" />

<img width="1788" alt="Image" src="https://github.com/user-attachments/assets/b3513d7a-c7f4-40a4-91cd-267e7b5c5e34" />

**Comment by mattatticus** [comment]
Yeah the open source bios seems to be the problem. It works with the official bios.

**Comment by skylersaleh** [comment]
I filed an issue on the tracker for the open source BIOS here: https://github.com/Cult-of-GBA/BIOS/issues/17

I'll close the issue here and grab the updated open source BIOS when it gets fixed.

**Comment by mattatticus** [comment]
Thanks for the quick response.
